spring:
  datasource:
    url: jdbc:postgresql://localhost/chronos
    username: postgres
    password: t9Cj4wAKSg2B
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
